# Generated by Django 4.0.6 on 2022-08-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alfajor',
            old_name='description',
            new_name='descripcion',
        ),
    ]
